#[derive(Clone, Debug, Eq, PartialEq)]
pub(crate) enum UiCommand {
    SelectNext,
    SelectPrevious,
    ScrollOlder,
    ScrollNewer,
    Quit,
    Insert(char),
    Paste(String),
    DeleteInput,
    InsertNewline,
    SubmitPrompt,
    CreateConversation,
    CycleProvider,
    CycleModel,
    CycleEffort,
    CycleMode,
    CyclePermission,
    CycleContext,
    SwitchSelection,
    FocusSessions,
    ToggleHelp,
    ToggleActivity,
    ToggleThinking,
    Interrupt,
}
